// Comprehensive US colleges database (top 200+)
export const collegesDB = [
  // Ivy League
  { name: "Harvard University", city: "Cambridge", state: "Massachusetts" },
  { name: "Yale University", city: "New Haven", state: "Connecticut" },
  { name: "Princeton University", city: "Princeton", state: "New Jersey" },
  { name: "Columbia University", city: "New York City", state: "New York" },
  { name: "University of Pennsylvania", city: "Philadelphia", state: "Pennsylvania" },
  { name: "Brown University", city: "Providence", state: "Rhode Island" },
  { name: "Dartmouth College", city: "Hanover", state: "New Hampshire" },
  { name: "Cornell University", city: "Ithaca", state: "New York" },
  
  // Top Private Universities
  { name: "Stanford University", city: "Stanford", state: "California" },
  { name: "Massachusetts Institute of Technology", city: "Cambridge", state: "Massachusetts" },
  { name: "Duke University", city: "Durham", state: "North Carolina" },
  { name: "Northwestern University", city: "Evanston", state: "Illinois" },
  { name: "Johns Hopkins University", city: "Baltimore", state: "Maryland" },
  { name: "California Institute of Technology", city: "Pasadena", state: "California" },
  { name: "University of Chicago", city: "Chicago", state: "Illinois" },
  { name: "Vanderbilt University", city: "Nashville", state: "Tennessee" },
  { name: "Rice University", city: "Houston", state: "Texas" },
  { name: "Washington University in St. Louis", city: "St. Louis", state: "Missouri" },
  { name: "Emory University", city: "Atlanta", state: "Georgia" },
  { name: "Georgetown University", city: "Washington", state: "District of Columbia" },
  { name: "Carnegie Mellon University", city: "Pittsburgh", state: "Pennsylvania" },
  { name: "University of Notre Dame", city: "Notre Dame", state: "Indiana" },
  { name: "University of Southern California", city: "Los Angeles", state: "California" },
  { name: "New York University", city: "New York City", state: "New York" },
  { name: "Tufts University", city: "Medford", state: "Massachusetts" },
  { name: "Boston College", city: "Chestnut Hill", state: "Massachusetts" },
  { name: "Boston University", city: "Boston", state: "Massachusetts" },
  { name: "Case Western Reserve University", city: "Cleveland", state: "Ohio" },
  { name: "Northeastern University", city: "Boston", state: "Massachusetts" },
  { name: "Tulane University", city: "New Orleans", state: "Louisiana" },
  { name: "University of Rochester", city: "Rochester", state: "New York" },
  { name: "Wake Forest University", city: "Winston-Salem", state: "North Carolina" },
  { name: "Lehigh University", city: "Bethlehem", state: "Pennsylvania" },
  { name: "Brandeis University", city: "Waltham", state: "Massachusetts" },
  { name: "Rensselaer Polytechnic Institute", city: "Troy", state: "New York" },
  { name: "Syracuse University", city: "Syracuse", state: "New York" },
  { name: "Pepperdine University", city: "Malibu", state: "California" },
  { name: "Villanova University", city: "Villanova", state: "Pennsylvania" },
  
  // Top Public Universities
  { name: "University of California, Berkeley", city: "Berkeley", state: "California" },
  { name: "University of California, Los Angeles", city: "Los Angeles", state: "California" },
  { name: "University of Michigan", city: "Ann Arbor", state: "Michigan" },
  { name: "University of Virginia", city: "Charlottesville", state: "Virginia" },
  { name: "University of North Carolina at Chapel Hill", city: "Chapel Hill", state: "North Carolina" },
  { name: "University of California, San Diego", city: "San Diego", state: "California" },
  { name: "University of California, Santa Barbara", city: "Santa Barbara", state: "California" },
  { name: "University of California, Irvine", city: "Irvine", state: "California" },
  { name: "University of California, Davis", city: "Davis", state: "California" },
  { name: "University of Florida", city: "Gainesville", state: "Florida" },
  { name: "Georgia Institute of Technology", city: "Atlanta", state: "Georgia" },
  { name: "University of Texas at Austin", city: "Austin", state: "Texas" },
  { name: "University of Washington", city: "Seattle", state: "Washington" },
  { name: "University of Wisconsin-Madison", city: "Madison", state: "Wisconsin" },
  { name: "University of Illinois Urbana-Champaign", city: "Urbana-Champaign", state: "Illinois" },
  { name: "Ohio State University", city: "Columbus", state: "Ohio" },
  { name: "Pennsylvania State University", city: "University Park", state: "Pennsylvania" },
  { name: "Purdue University", city: "West Lafayette", state: "Indiana" },
  { name: "University of Maryland", city: "College Park", state: "Maryland" },
  { name: "University of Georgia", city: "Athens", state: "Georgia" },
  { name: "Texas A&M University", city: "College Station", state: "Texas" },
  { name: "Rutgers University", city: "New Brunswick", state: "New Jersey" },
  { name: "University of Minnesota", city: "Minneapolis", state: "Minnesota" },
  { name: "University of Pittsburgh", city: "Pittsburgh", state: "Pennsylvania" },
  { name: "Virginia Tech", city: "Blacksburg", state: "Virginia" },
  { name: "University of Connecticut", city: "Storrs", state: "Connecticut" },
  { name: "University of Massachusetts Amherst", city: "Amherst", state: "Massachusetts" },
  { name: "University of Delaware", city: "Newark", state: "Delaware" },
  { name: "University of Iowa", city: "Iowa City", state: "Iowa" },
  { name: "Indiana University Bloomington", city: "Bloomington", state: "Indiana" },
  { name: "Michigan State University", city: "East Lansing", state: "Michigan" },
  { name: "University of Colorado Boulder", city: "Boulder", state: "Colorado" },
  { name: "University of Arizona", city: "Tucson", state: "Arizona" },
  { name: "Arizona State University", city: "Tempe", state: "Arizona" },
  { name: "University of Oregon", city: "Eugene", state: "Oregon" },
  { name: "University of Utah", city: "Salt Lake City", state: "Utah" },
  { name: "Clemson University", city: "Clemson", state: "South Carolina" },
  { name: "Auburn University", city: "Auburn", state: "Alabama" },
  { name: "University of Alabama", city: "Tuscaloosa", state: "Alabama" },
  { name: "University of Tennessee", city: "Knoxville", state: "Tennessee" },
  { name: "University of Kentucky", city: "Lexington", state: "Kentucky" },
  { name: "University of South Carolina", city: "Columbia", state: "South Carolina" },
  { name: "University of Oklahoma", city: "Norman", state: "Oklahoma" },
  { name: "University of Kansas", city: "Lawrence", state: "Kansas" },
  { name: "University of Nebraska-Lincoln", city: "Lincoln", state: "Nebraska" },
  { name: "Iowa State University", city: "Ames", state: "Iowa" },
  { name: "University of Missouri", city: "Columbia", state: "Missouri" },
  { name: "University of Arkansas", city: "Fayetteville", state: "Arkansas" },
  { name: "University of Mississippi", city: "Oxford", state: "Mississippi" },
  { name: "Louisiana State University", city: "Baton Rouge", state: "Louisiana" },
  { name: "University of New Mexico", city: "Albuquerque", state: "New Mexico" },
  { name: "University of Nevada, Reno", city: "Reno", state: "Nevada" },
  { name: "University of Hawaii at Manoa", city: "Honolulu", state: "Hawaii" },
  { name: "University of Alaska Fairbanks", city: "Fairbanks", state: "Alaska" },
  { name: "University of Vermont", city: "Burlington", state: "Vermont" },
  { name: "University of New Hampshire", city: "Durham", state: "New Hampshire" },
  { name: "University of Maine", city: "Orono", state: "Maine" },
  { name: "University of Rhode Island", city: "Kingston", state: "Rhode Island" },
  
  // Liberal Arts Colleges
  { name: "Williams College", city: "Williamstown", state: "Massachusetts" },
  { name: "Amherst College", city: "Amherst", state: "Massachusetts" },
  { name: "Swarthmore College", city: "Swarthmore", state: "Pennsylvania" },
  { name: "Pomona College", city: "Claremont", state: "California" },
  { name: "Wellesley College", city: "Wellesley", state: "Massachusetts" },
  { name: "Bowdoin College", city: "Brunswick", state: "Maine" },
  { name: "Carleton College", city: "Northfield", state: "Minnesota" },
  { name: "Claremont McKenna College", city: "Claremont", state: "California" },
  { name: "Middlebury College", city: "Middlebury", state: "Vermont" },
  { name: "Davidson College", city: "Davidson", state: "North Carolina" },
  { name: "Colgate University", city: "Hamilton", state: "New York" },
  { name: "Haverford College", city: "Haverford", state: "Pennsylvania" },
  { name: "Vassar College", city: "Poughkeepsie", state: "New York" },
  { name: "Hamilton College", city: "Clinton", state: "New York" },
  { name: "Grinnell College", city: "Grinnell", state: "Iowa" },
  { name: "Smith College", city: "Northampton", state: "Massachusetts" },
  { name: "Colby College", city: "Waterville", state: "Maine" },
  { name: "Bates College", city: "Lewiston", state: "Maine" },
  { name: "Oberlin College", city: "Oberlin", state: "Ohio" },
  { name: "Macalester College", city: "St. Paul", state: "Minnesota" },
  { name: "Bryn Mawr College", city: "Bryn Mawr", state: "Pennsylvania" },
  { name: "Colorado College", city: "Colorado Springs", state: "Colorado" },
  { name: "Kenyon College", city: "Gambier", state: "Ohio" },
  { name: "Reed College", city: "Portland", state: "Oregon" },
  { name: "Occidental College", city: "Los Angeles", state: "California" },
  
  // Regional Universities
  { name: "Western Washington University", city: "Bellingham", state: "Washington" },
  { name: "Eastern Washington University", city: "Cheney", state: "Washington" },
  { name: "Central Washington University", city: "Ellensburg", state: "Washington" },
  { name: "Washington State University", city: "Pullman", state: "Washington" },
  { name: "Gonzaga University", city: "Spokane", state: "Washington" },
  { name: "Seattle University", city: "Seattle", state: "Washington" },
  { name: "University of Portland", city: "Portland", state: "Oregon" },
  { name: "Portland State University", city: "Portland", state: "Oregon" },
  { name: "Oregon State University", city: "Corvallis", state: "Oregon" },
  { name: "Boise State University", city: "Boise", state: "Idaho" },
  { name: "University of Idaho", city: "Moscow", state: "Idaho" },
  { name: "Montana State University", city: "Bozeman", state: "Montana" },
  { name: "University of Montana", city: "Missoula", state: "Montana" },
  { name: "University of Wyoming", city: "Laramie", state: "Wyoming" },
  { name: "Colorado State University", city: "Fort Collins", state: "Colorado" },
  { name: "University of Denver", city: "Denver", state: "Colorado" },
  { name: "University of San Diego", city: "San Diego", state: "California" },
  { name: "Loyola Marymount University", city: "Los Angeles", state: "California" },
  { name: "Santa Clara University", city: "Santa Clara", state: "California" },
  { name: "Chapman University", city: "Orange", state: "California" },
  { name: "University of the Pacific", city: "Stockton", state: "California" },
  { name: "San Diego State University", city: "San Diego", state: "California" },
  { name: "San Jose State University", city: "San Jose", state: "California" },
  { name: "California State University, Long Beach", city: "Long Beach", state: "California" },
  { name: "California Polytechnic State University", city: "San Luis Obispo", state: "California" },
  { name: "University of San Francisco", city: "San Francisco", state: "California" },
  { name: "Fordham University", city: "Bronx", state: "New York" },
  { name: "Hofstra University", city: "Hempstead", state: "New York" },
  { name: "Ithaca College", city: "Ithaca", state: "New York" },
  { name: "Marist College", city: "Poughkeepsie", state: "New York" },
  { name: "Pace University", city: "New York City", state: "New York" },
  { name: "St. John's University", city: "Queens", state: "New York" },
  { name: "SUNY Binghamton", city: "Binghamton", state: "New York" },
  { name: "SUNY Buffalo", city: "Buffalo", state: "New York" },
  { name: "SUNY Stony Brook", city: "Stony Brook", state: "New York" },
  { name: "Drexel University", city: "Philadelphia", state: "Pennsylvania" },
  { name: "Temple University", city: "Philadelphia", state: "Pennsylvania" },
  { name: "Duquesne University", city: "Pittsburgh", state: "Pennsylvania" },
  { name: "Loyola University Chicago", city: "Chicago", state: "Illinois" },
  { name: "DePaul University", city: "Chicago", state: "Illinois" },
  { name: "Illinois Institute of Technology", city: "Chicago", state: "Illinois" },
  { name: "Marquette University", city: "Milwaukee", state: "Wisconsin" },
  { name: "Creighton University", city: "Omaha", state: "Nebraska" },
  { name: "University of Dayton", city: "Dayton", state: "Ohio" },
  { name: "Xavier University", city: "Cincinnati", state: "Ohio" },
  { name: "Miami University", city: "Oxford", state: "Ohio" },
  { name: "University of Cincinnati", city: "Cincinnati", state: "Ohio" },
  { name: "Butler University", city: "Indianapolis", state: "Indiana" },
  { name: "Valparaiso University", city: "Valparaiso", state: "Indiana" },
  { name: "University of Detroit Mercy", city: "Detroit", state: "Michigan" },
  { name: "Wayne State University", city: "Detroit", state: "Michigan" },
  { name: "University of Miami", city: "Coral Gables", state: "Florida" },
  { name: "Florida State University", city: "Tallahassee", state: "Florida" },
  { name: "University of Central Florida", city: "Orlando", state: "Florida" },
  { name: "University of South Florida", city: "Tampa", state: "Florida" },
  { name: "Florida International University", city: "Miami", state: "Florida" },
  { name: "Rollins College", city: "Winter Park", state: "Florida" },
  { name: "Stetson University", city: "DeLand", state: "Florida" },
  { name: "University of Tampa", city: "Tampa", state: "Florida" },
  { name: "Elon University", city: "Elon", state: "North Carolina" },
  { name: "High Point University", city: "High Point", state: "North Carolina" },
  { name: "Furman University", city: "Greenville", state: "South Carolina" },
  { name: "College of Charleston", city: "Charleston", state: "South Carolina" },
  { name: "University of Richmond", city: "Richmond", state: "Virginia" },
  { name: "James Madison University", city: "Harrisonburg", state: "Virginia" },
  { name: "Virginia Commonwealth University", city: "Richmond", state: "Virginia" },
  { name: "George Mason University", city: "Fairfax", state: "Virginia" },
  { name: "American University", city: "Washington", state: "District of Columbia" },
  { name: "George Washington University", city: "Washington", state: "District of Columbia" },
  { name: "Howard University", city: "Washington", state: "District of Columbia" },
  { name: "Loyola University Maryland", city: "Baltimore", state: "Maryland" },
  { name: "Towson University", city: "Towson", state: "Maryland" },
  { name: "University of Baltimore", city: "Baltimore", state: "Maryland" },
  { name: "Southern Methodist University", city: "Dallas", state: "Texas" },
  { name: "Texas Christian University", city: "Fort Worth", state: "Texas" },
  { name: "Baylor University", city: "Waco", state: "Texas" },
  { name: "University of Houston", city: "Houston", state: "Texas" },
  { name: "University of North Texas", city: "Denton", state: "Texas" },
  { name: "Texas Tech University", city: "Lubbock", state: "Texas" },
];
